DROP TABLE IF EXISTS invite_tokens;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS transfers;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS library_items;
DROP TABLE IF EXISTS peers;
